# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory
WORKDIR /projectMIR

# Copy the requirements file into the container
# COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the command to start the app
CMD ["python3", "Project_recherche.py"]